[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [
    { access = 'read', path = './configs' },
    { access = 'read', path = './test' },
    { access = 'write', path = './deployment.json' },
]

[rpc_endpoints]
optimism = "https://mainnet.optimism.io"
celo = "https://rpc.celopg.eco"

[etherscan]
optimism = { key = "UGB21JYI7XRY68M6IBNNYHPJYTSX2V5ATX" }
celo = { key = "I36FHHV8SEQP38FSSMQUCI92BJK4H5PJSE" }
